export const SERVICES = ['Prisma', 'Payway', 'MercadoPago']
export const FLAGS = ['visa', 'master', 'naranjax', 'mercadopago', 'cabal']
export const TYPE_CARDS = ['c', 'd']
export const MONTHS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
export const NUMBER_SIGNS = [1, -1]